export const BALANCE_FETCH_REQUEST = 'BALANCE_FETCH_REQUEST';
export const BALANCE_FETCH_SUCCESS = 'BALANCE_FETCH_SUCCESS';
export const BALANCE_FETCH_FAIL = 'BALANCE_FETCH_FAIL';

export const MONEY_TRANSFER_REQUEST = 'MONEY_TRANSFER_REQUEST';
export const MONEY_TRANSFER_SUCCESS = 'MONEY_TRANSFER_SUCCESS';
export const MONEY_TRANSFER_FAIL = 'MONEY_TRANSFER_FAIL';

export const MONEY_WITHDRAW_REQUEST = 'MONEY_WITHDRAW_REQUEST';
export const MONEY_WITHDRAW_SUCCESS = 'MONEY_WITHDRAW_SUCCESS';
export const MONEY_WITHDRAW_FAIL = 'MONEY_WITHDRAW_FAIL';

export const MONEY_DEPOSIT_REQUEST = 'MONEY_DEPOSIT_REQUEST';
export const MONEY_DEPOSIT_SUCCESS = 'MONEY_DEPOSIT_SUCCESS';
export const MONEY_DEPOSIT_FAIL = 'MONEY_DEPOSIT_FAIL';