export const USER_ACCOUNTS_REQUEST = 'USER_ACCOUNTS_REQUEST'
export const USER_ACCOUNTS_SUCCESS = 'USER_ACCOUNTS_SUCCESS'
export const USER_ACCOUNTS_FAIL = 'USER_ACCOUNTS_FAIL'


export const USER_ACCOUNT_CREATE_REQUEST = 'USER_ACCOUNT_CREATE_REQUEST'
export const USER_ACCOUNT_CREATE_SUCCESS = 'USER_ACCOUNT_CREATE_SUCCESS'
export const USER_ACCOUNT_CREATE_FAIL = 'USER_ACCOUNT_CREATE_FAIL'